/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    App classUnderTest;
    @Before
    public void setup() {
        classUnderTest = new App();
    }
    @Test public void appHasAGreeting() {
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void appHasAHello() {
        assertEquals("Hello World!", classUnderTest.getGreeting());
    }
}
