/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import org.junit.Before;
import org.junit.Test;
import pacman.Game;
import pacman.utility.GameCallback;
import pacman.utility.PropertiesLoader;

import java.util.Properties;

import static org.junit.Assert.*;

public class AppTest {
    App classUnderTest;
    @Before
    public void setup() {
        classUnderTest = new App();
    }
    @Test
    public void testPacManWinSuccess() {
        String propertiesPath = "properties/test2.properties";
        final Properties properties = PropertiesLoader.loadPropertiesFile(propertiesPath);
        GameCallback gameCallback = new GameCallback();
        Game game = new Game(gameCallback, properties);
        String logResult = game.runGame(false);
        assertTrue(logResult.contains("Score: 16. Pills: 8"));
        assertTrue(logResult.contains("YOU WIN"));
    }

    @Test
    public void testPacManWinFailed() {
        String propertiesPath = "properties/test2.properties";
        final Properties properties = PropertiesLoader.loadPropertiesFile(propertiesPath);
        GameCallback gameCallback = new GameCallback();
        Game game = new Game(gameCallback, properties);
        String logResult = game.runGame(false);
        assertTrue(logResult.contains("Score: 17. Pills: 8"));
        assertTrue(logResult.contains("YOU LOSE"));
    }
}
